// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRP.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260912083908_Restructure")]
    partial class Restructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("HRP.FoodBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FoodId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LocationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OpenedDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhysDataRecId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Quantity")
                        .HasColumnType("REAL");

                    b.Property<float>("QuantityConsumed")
                        .HasColumnType("REAL");

                    b.Property<bool>("isOpen")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("PhysDataRecId");

                    b.ToTable("FoodBatches");
                });

            modelBuilder.Entity("HRP.PhysDataRec", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PhysDataRec");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PhysDataRec");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("HRP.Food", b =>
                {
                    b.HasBaseType("HRP.PhysDataRec");

                    b.Property<int?>("ClosedLifespanDays")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsExpirable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpenLifespanDays")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("Food");
                });

            modelBuilder.Entity("HRP.FoodBatch", b =>
                {
                    b.HasOne("HRP.Food", null)
                        .WithMany("Batches")
                        .HasForeignKey("FoodId");

                    b.HasOne("HRP.PhysDataRec", "Item")
                        .WithMany()
                        .HasForeignKey("PhysDataRecId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("HRP.Food", b =>
                {
                    b.Navigation("Batches");
                });
#pragma warning restore 612, 618
        }
    }
}
